# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('nb_views', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('deletion_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Bineta.Document')),
            ],
            options={
                'db_table': 'DocumentFile',
            },
        ),
    ]
